### PR TITLE
feat: add Chinese translations for Hong Kong (zh-HK), Taiwan (zh-TW) and China (zh-CN) locales

### PR DESCRIPTION
**Pull request by neotan**

### CODE REVIEW

**Comment by yagil** [comment]
Thank you @neotan for the contribution!

**Comment by Tilannlou** [comment]
Are they compatible with the latest version of the program?

**Comment by yagil** [comment]
@Tilannlou will be available in 0.3.3 which is coming soon, but not yet out.  ETA this week

**Comment by Tilannlou** [comment]
如何將LM STUDIO設定語言增加中文選項

**Pull request merged**
