### PR TITLE
pt_PT translation

### PR DESCRIPTION
**Pull request by catarino**

### CODE REVIEW

**Comment by catarino** [comment]
Added .DS_Store file to .gitignore but it's still included in PR. Don't quite understand why…

**Comment by catarino** [comment]
Would be nice to have some reviews from other native pt_PTs :)

**Comment by yagil** [comment]
@catarino thank you for the contribution!

Regarding the `.gitignore` file as well as `.DS_Store`. Let's please remove them.

I asked [Codestral](https://huggingface.co/lmstudio-community/Codestral-22B-v0.1-GGUF) for help, and here's its response:

image

**Comment by catarino** [comment]
Hi @yagil thank you


that didn't quite worked, but I managed to fix it with  `find . -name ".DS_Store" -type f -delete` and find . -name ".gitignore" -type f -delete. 

In any case I'll close this request and open another one to make it clean.

**Pull request closed without merging**
