### PR TITLE
Add Japanese localization

### PR DESCRIPTION
**Pull request by digitalsp**
Added Japanese translation

'Japanese' <-> '日本語'

### CODE REVIEW

**Comment by yagil** [comment]
@digitalsp thank you for the contribution! I've been looking forward to a Japanese translation, thank you for it.

I see that you are targeting the `dev` branch which can sometimes be a good idea, but since we're making rapid changes to it it's best to target `main` instead. 

I just synchronized `dev` and `main`. Would you be able to update your PR to point to `main` instead?  

Thank you once again!

**Comment by digitalsp** [comment]
Understood. I'll change the target to main.

**Comment by yagil** [comment]
Thank you @digitalsp ! You will also likely need to fetch the latest main rebase on top of it. Are you familiar with this process? If not, I could assist further

**Comment by digitalsp** [comment]
@yagil Ok.
Excuse me, I'm little busy, can you wait a day, I'll do it after a day...

**Comment by yagil** [comment]
> @yagil Ok. Excuse me, I'm little busy, can you wait a day, I'll do it after a day...

whenever you find the time, thank you again!

**Comment by digitalsp** [comment]
Sorry, I am late, but I think it is probably done. Please confirm.

**Comment by yagil** [comment]
Hello @digitalsp thank you!!!!   This is probably `git` itself just being stubborn, but there are a few unrelated changes in the PR.  I can help by making a new PR with your changes.  This will be the order of operations:

1. If you're OK with it, I will create a new PR with **your** changes
2. we will close this PR
3. merge the new PR

How does this sound?

**Comment by yagil** [comment]
Actually this commit is perfect `1267e913f23f953d5b266df308146d0fad6c2ed1`.  Just need to drop the other one.  Please let me know if you need assistance with it

**Comment by yagil** [comment]
I created this draft pull request here: https://github.com/lmstudio-ai/localization/pull/101, please let me know your preference

**Comment by digitalsp** [comment]
@yagil Sure. That's fine.

**Comment by yagil** [comment]
Thank you @digitalsp!

**Pull request closed without merging**
