### PR TITLE
Add zh folder and JSON files (i.e., Chinese)

### PR DESCRIPTION
**Pull request by bladeswill**
Add zh folder and JSON files (i.e., Chinese)

### CODE REVIEW

**Comment by kywarai** [comment]
Would you mind using zh-Hans instead of just zh?

**Comment by bladeswill** [comment]
> 您介意使用 zh-Hans 而不仅仅是 zh 吗？



> Would you mind using zh-Hans instead of just zh?

I agree, but don't know how to fix it

**Comment by bladeswill** [comment]
> > Would you mind using zh-Hans instead of just zh?
> 
> I agree, but don't know how to fix it

I'm not familiar with GitHub's operations, so if anyone could make any improvements to this issue or the content of the translation file, I'd be grateful.

**Comment by kywarai** [comment]
> > > Would you mind using zh-Hans instead of just zh?
> > 
> > 
> > I agree, but don't know how to fix it
> 
> I'm not familiar with GitHub's operations, so if anyone could make any improvements to this issue or the content of the translation file, I'd be grateful.

Thank you. 
Don't worry, I'll make the corrections in a future Pull Request.

**Pull request closed without merging**
